version: "3"
services:
  ecommercedb:
    container_name: ecommerce_db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    container_name: sangwon_redis
    image: "redis:alpine"
    env_file:
      - .env
    ports:
      - 6379:6379
