version: "3"
services:
  ecommercedb:
    container_name: ecommerce_db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    container_name: ecommerce_redis
    image: "redis:alpine"
    env_file:
      - .env
    ports:
      - 6379:6379

  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio_data:/data
    env_file:
      - .env
